### ISSUE TITLE
Ordering of dots of division

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#105]
Mensural notation allows for dots of division, and PAE uses the `.` to indicate this. 

However, in CWMN PAE the dot must follow the duration value to indicate a dot of augmentation. 

This is just a sense check to see if it's still OK for the dot of division in Mensural to also follow the duration value? Or should it be placed somewhere else?

**Comment by lpugin** [comment]
Yes, I think it is fine to have it following the duration in mensural notation too and not as division dots. In my opinion we should see mensural PAEC not as strict mensural notation. Generally speaking, I am willing to revise the Verovio implementation and focus only on the visual aspect. This would mean a few points to be relaxed, including allowing multiple dots, which are clearly duration dots.

**Comment by ahankinson** [comment]
OK; does that mean that the duration is also required for a dot of division? In other words, would you ever need just the dot and no duration?

**Comment by lpugin** [comment]
I don't think we have (and will have) such thing as a division dot. So I would not expect to see just the dot. So it is really some pseudo-mensural notation.

**Comment by ahankinson** [comment]
OK... so should I remove this paragraph? 

```
                For Mensural notation the period character <code>.</code> MAY be used to indicate a dot of division to
                alter the interpretation of ternary values. Multiple successive dots of division MUST NOT occur.
```
