### ISSUE TITLE
Limit the number of dots that can be used

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#144]
Currently there is no limit to the number of duration dots that can be specified. I would suggest three.

**Comment by lpugin** [comment]
Maybe 4? https://rism.online/sources/1001291680

**Comment by ahankinson** [comment]
4 is also OK.

**Comment by BaMikusi** [comment]
This Liszt example is really extreme and arguably the limit beyond which one should no longer use dotting but some other notation (simply to make sure the performer can actually read it). So 4 is surely fine as the upper limit.
