### ISSUE TITLE
Default values in incipits?

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/pae-code-spec#24]
So far RISM catalogers haven't had to declare initial octave or duration if beginning in the first octave after Middle C with quarter notes. Therefore, ```CDEF``` displays as intended even if ```'4CDEF``` would, strictly speaking, be required. 
![image](https://user-images.githubusercontent.com/18663291/149546339-ea5031b4-8f50-4c6a-aa9a-c62623eedb3c.png)

Not sure if this is a Verovio thing or a spec thing, if it is even desirable to have these defaults built in? Or maybe that's just been local RISM practice for years?

Even ```{CD}``` defaults to 8th notes at the beginning of a measure:
![image](https://user-images.githubusercontent.com/18663291/149547792-60a56f49-ae68-42cd-aab5-6d72decd6f76.png)

**Comment by ahankinson** [comment]
An older and wiser me is now revisiting this issue, and I think there is now some value in allowing for "default" values. 

We use an assumed 4th octave and quarter-note pitch for the PAE input on the incipit search on RISM Online, and the use case there is that it means that users do not have to specify these things if they simply want to search a melodic sequence. 

We also supply a number of shorthand codes -- you can omit the octave or duration for any given pitch, and it will assume it's the one previously supplied. If we want to keep this, then we either have to accept that there can be all default values, or at least one octave or duration supplied at the beginning of the encoding. 

And then there's neume notation, which may not require any duration to be supplied at all, if we go in that direction.

So, I would now say that as long as the defaults are clearly defined in the spec, that we can allow them.

**Comment by lpugin** [comment]
I am fine with a default `'4`. I am not too sure with `{CD}` being default to 8th notes, though, but maybe this is acceptable too. The main point is that is needs to be clearly documented.

**Comment by ahankinson** [comment]
I don't think `{}` should, in effect, apply an implicit `8`, since it's not clear what this should be:

`B{CD}E`

Is that `4B{8C8D}4E` or `4B{8C8D}8E`? Probably best to avoid this and just say that beams of notes that are less than "8" is not allowed.

**Comment by lpugin** [comment]
Yes, I agree. I should fix Verovio accordingly. This will also be another issue for @carlolic to check.

**Comment by ahankinson** [comment]
I think this is addressed now.
