### ISSUE TITLE
Subfield $s, coded validity note

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/pae-code-spec#25]
What does the future of $s look like? In Plaine & Easie officially it is allowed: 
```
5. Coded validity note
A one-character coded validity note can be introduced by a '~' at the end of the code.
Accepted characters are:

?	a mistake in the incipit has not been corrected
+	a mistake in the incipit has been corrected
t	incipit has been transcribed into modern notation
```
https://www.iaml.info/plaine-easie-code#toc-5

But starting with Muscat, we don't want to use it any more:
```
Validity (031 $s)
Do not enter anything into this field! (It is only used for old data.)
```
The reasoning is because someone seeing a "+" etc. in a record wouldn't intuitively know what was meant, and if changes were made then you would just say so in a note, without the encoded character.

I see that $s is only used ca. 2,500 times. I haven't checked for ~ at the end of the code though.

I'd like to propose a Muscat validation that creates a warning if $s is filled out (we don't want the field to be used, but people might accidently use it)  but I thought I'd ask here first.

**Comment by ahankinson** [comment]
Having looked at, I'm going to suggest we drop the coded validity note altogether from the Plaine & Easie specification, for the following reasons:

1. It's already fully described in the MARC documentation;
2. It's specific to MARC/UNIMARC representations; the other representations (string code, etc.) do not have them;
3. It's *not* specific to the PAE music notation, and it can reference text incipits or other subfields in 031 that we do not describe in the PAE specifications. (We don't describe the `$m` subfield for example).
