### ISSUE TITLE
Decide on order of naturals in cancellations

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#58]
@lpugin: I think we need to decide if n MAY be given (for example when changing from xFCG to nxF. If yes, we also need to decide the allowed order(s).

@ahankinson : We should handle this in the section on inline changes to key signatures. 

From #54

**Comment by ahankinson** [comment]
We currently have the following statement: 

"It is not necessary to cancel the previous key signature with naturals when defining a new key signature."

The question is whether we should keep this statement, or whether we should do something about cancellations. My current take is that the new key signature should simply be declared, and the renderer can decide whether or not to show naturals.

If so, then this can be closed, but there may be a use case that I am missing here.

**Comment by lpugin** [comment]
The only case where we really need `n` is when a previous key signature is changing to C-major/a-minor. In that case, we can expect just `$n`, or `$nFCG` for cancelling 3 sharps. But then the problem is what to expect for the order, so just `$n` would actually be better. This might need changing some of our data, though.

**Comment by lpugin** [comment]
If there is no objection, then I would suggest just `$n` to be allowed

**Comment by ahankinson** [comment]
Yeah, the current version of the spec states that there is no need to cancel a prevailing key signature, so the only use for $n is either a) at the initial key signature to mark that a natural key sig is present, or b) to change from a key signature with accidentals to one without.
