### ISSUE TITLE
Alternating time signature representation

### ISSUE THREAD

**Issue by lpugin** [rism-digital/pae-code-spec#64]
Currently, alternating time signatures are represented with time signature factions separated with a space.

The space is problematic because it should be reserved for coding the end of a time signature. It is actually in contradiction with the clarification suggested in #63 and expecting no space to be included before data starts.

The means that we need to defined another character for delimitating fractions in alternating time signatures.

**Comment by lpugin** [comment]
Duplicates with #103

**Comment by ahankinson** [comment]
Oh, good catch. I didn't see this.
