### ISSUE TITLE
Allow square brackets to indicate a time signature was supplied

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#71]
Similar to how square brackets are used for supplied key signatures, we may wish to also allow for supplied time signatures. 

If we do allow it, we should only allow brackets around the entire time signature and not around any given component of that time signature. e.g., `[3/2]`, not `3[/2]`.

**Comment by BaMikusi** [comment]
Sounds feasible. But then the [square bracket] option should also be available for clefs, especially if entering one will be required, even if in the source there is none.

**Comment by lpugin** [comment]
I would prefer not to add that. I think it has been allowed on key signature accidentals because otherwise the sounding pitch would be wrong. The time signature is less of an issue in that regard - a least for CWMN. 

If we were doing it, then I agree it should be available for clefs too.

**Comment by ahankinson** [comment]
Similar to #70 , the time signature is not necessary for accurately representing written or sounding pitch. Thus if it is not present in the original, then the time signature should be omitted, and not supplied. It will be an error to enclosed a time signature in `[]`.
