### ISSUE TITLE
Disallow rests within ties

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/pae-code-spec#88]
The following PAE:

`1''G+/-+/G`

Currently produces (in Verovio):

<img width="305" alt="image" src="https://github.com/rism-digital/pae-code-spec/assets/163183/ff0c59d6-535f-41f2-ad63-166993dec409">

I think there's a problem with Verovio here (it probably shouldn't tie the first and last notes together) but we probably also want to prohibit ties to rests? Unless someone can think of a use case for allowing them.

**Comment by jenniferward** [comment]
At least the error is flagged: `A tie using '+' must be followed by a note.`

If I searched correctly, I only found `-+` in 10 records and none are displaying like this. I don't know what was going on but if you delete the `+` in 8 of them then the beat count is still correct, so it could have just been a stray keystroke that the cataloger didn't notice. In one case I think a `/` was meant instead (and in the last case the cataloger should take a look themselves).

https://muscat.rism.info/admin/sources/201005443/edit
https://muscat.rism.info/admin/sources/410001760/edit
https://muscat.rism.info/admin/sources/659400098/edit
https://muscat.rism.info/admin/sources/703002876/edit
https://muscat.rism.info/admin/sources/703004171/edit
https://muscat.rism.info/admin/sources/840018939/edit
https://muscat.rism.info/admin/sources/853001953/edit
https://muscat.rism.info/admin/sources/1001030941/edit
https://muscat.rism.info/admin/sources/1001079338/edit
https://muscat.rism.info/admin/sources/1001096940/edit

I can't find any use cases in our data, and if no one objects then I'm happy to correct these 10.

**Comment by ahankinson** [comment]
I'm happy to explicitly disallow rests and ties. I just altered the title to reflect this.
